# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-14 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_char', models.CharField(help_text='Row character', max_length=128)),
                ('total_seats', models.IntegerField(db_index=True, help_text='The size of the resource')),
            ],
            options={
                'verbose_name_plural': 'Rows',
                'db_table': 'screens_row',
                'verbose_name': 'Row',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(help_text='Screen name', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_screens', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_screens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Screens',
                'db_table': 'screens_screen',
                'verbose_name': 'Screen',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField(db_index=True, help_text='The seat no.')),
                ('is_aisle_seat', models.BooleanField(db_index=True, default=False, help_text='Is is it an aisle seat?', verbose_name='Is is it an aisle seat?')),
                ('is_reserved', models.BooleanField(db_index=True, default=False, help_text='Reserve a seat', verbose_name='Has the seat been reserved?')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reserved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Seats',
                'db_table': 'screens_seat',
                'verbose_name': 'Seat',
            },
        ),
        migrations.AddField(
            model_name='row',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='screens.Screen'),
        ),
        migrations.AddField(
            model_name='row',
            name='seats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='screens.Seat'),
        ),
    ]
