# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-14 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='seats',
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='screens.Row'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='reserved_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
